# Generated by Django 3.2 on 2021-05-27 05:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('content', models.TextField()),
                ('publishing_date', models.DateTimeField(auto_now_add=True)),
                ('image', models.ImageField(upload_to='')),
                ('slug', models.SlugField(editable=False, max_length=130, unique=True)),
                ('featured', models.BooleanField(default=False)),
                ('topic', models.CharField(choices=[('Sport', 'Sport'), ('Technology', 'Technology'), ('Business', 'Business'), ('Entertainment', 'Entertainment')], max_length=120)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-publishing_date'],
            },
        ),
    ]
